# Numpy

In [1]:
import numpy as np

### Массивы

##### Одномерные

In [3]:
# передаем строку
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
# изменяем тит данных
a = np.array([1, 2, 3.6], dtype=str)
print(a)

['1' '2' '3.6']


In [6]:
# доступ к элементам массива
print('По индексу:', a[1])
print('По отрицательному индексу:', a[-1])
print('По срезу:', a[1:2])

По индексу: 2
По отрицательному индексу: 3.6
По срезу: ['2']


##### Двумерные

In [8]:
A = np.array([[1, 2, 3, 1], 
              [4, 5, 6, 4], 
              [7, 8, 9, 7]])
print(A)
print(f"Размерность A: {A.ndim}")
print(f"Форма A: {A.shape}")
print(f"Общее количество элементов: {A.size}")

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]
Размерность A: 2
Форма A: (3, 4)
Общее количество элементов: 12


In [9]:
#доступ к элементам массива
print(f'По индексу {A[0, 0]}')
print(f'По срезу {A[0:3, :2]}')

По индексу 1
По срезу [[1 2]
 [4 5]
 [7 8]]


При использовании срезов создается представление оригинального массива, а не новый массив.

In [11]:
# Создание нового массивас помощью среза из другого
C = A[1:3, 2:4].copy()
print(C)

[[6 4]
 [9 7]]


### Векторы

In [12]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])

In [20]:
print(f'Складывание с помощью "+":\t {a + b}')
print(f'Складывание с помощью "np.add":\t {np.add(a, b)}')
print(f'Вычитание с помощью "-":\t {a - b}')
print(f'Вычитание с помощью "np.subtract":\t {np.subtract(a, b)}')
print(f'Умножение вектора на скаляр с помощью "*":\t {a * 3}')
print(f'Умножение вектора на скаляр с помощью "np.multiply":\t {np.multiply(a, 3)}')
print(f'Умножение вектора на скаляр с помощью "np.dot":\t {np.dot(a, 3)}')
print(f'Умножение вектора на скаляр с помощью "a.dot":\t {a.dot(3)}')

Складывание с помощью "+":	 [ 5  7  9 11 13]
Складывание с помощью "np.add":	 [ 5  7  9 11 13]
Вычитание с помощью "-":	 [-5 -5 -5 -5 -5]
Вычитание с помощью "np.subtract":	 [-5 -5 -5 -5 -5]
Умножение вектора на скаляр с помощью "*":	 [ 0  3  6  9 12]
Умножение вектора на скаляр с помощью "np.multiply":	 [ 0  3  6  9 12]
Умножение вектора на скаляр с помощью "np.dot":	 [ 0  3  6  9 12]
Умножение вектора на скаляр с помощью "a.dot":	 [ 0  3  6  9 12]


In [19]:
print(f'Скалярное произведение векторов с помощью "a.dot":\t {a.dot(b)}')
print(f'Скалярное произведение векторов  с помощью "@":\t {a @ b}')

Скалярное произведение векторов с помощью "a.dot":	 80
Скалярное произведение векторов  с помощью "@":	 80


### Матрицы

In [28]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [29]:
print(f'Складывание с помощью "+":\n {A + B}')
print(f'Складывание с помощью "np.add":\n {np.add(A, B)}')
print(f'Вычитание с помощью "-":\n {A - B}')
print(f'Вычитание с помощью "np.subtract":\n {np.subtract(A, B)}')
print(f'Умножение матрицы на скаляр:\n {A * 3}')

Складывание с помощью "+":
 [[ 6  8]
 [10 12]
 [14 16]]
Складывание с помощью "np.add":
 [[ 6  8]
 [10 12]
 [14 16]]
Вычитание с помощью "-":
 [[-6 -6]
 [-6 -6]
 [-6 -6]]
Вычитание с помощью "np.subtract":
 [[-6 -6]
 [-6 -6]
 [-6 -6]]
Умножение матрицы на скаляр:
 [[ 0  3]
 [ 6  9]
 [12 15]]


##### Умножение матриц
Матрицы $A$ и $B$ можно умножить друг на друга, если _число столбцов_ первой матрицы равняется _числу строк_ второй матрицы. То есть если $A$ - матрица размера $n \times k$, то матрица $B$ должна иметь размер $k \times m$ для некоторого $m$.  
В таком случае результатом умножения будет матрица $C$ размера $n \times m$ (т.е. у неё будет строк как у первой матрицы, а столбцов - как у второй).

In [30]:
A = np.array([[1, 0, -1],
              [3, 5, -4]])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
C = A.dot(B)
print(C)

[[-6 -6 -6]
 [-5 -1  3]]


Если перемножаемые матрицы являются квадратными, то результат их умножения будет снова квадратной матрицей, причём, того же размера. Это означает, что квадратную матрицу можно возводить в степень. В `numpy` это можно делать с помощью функции `matrix_power` из модуля `numpy.linalg`:

In [24]:
D = np.linalg.matrix_power(B, 3)
print(D)

[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


##### Единичная и транспонированная матрица

In [31]:
print(f'Единичная матрица:\n {np.eye(3)}')
print(f'Транспонированная матрица с помощью функции "np.transpose"\n {np.transpose(A)}')
print(f'Транспонированная матрица с помощью метода "A.transpose"\n {A.transpose()}')
print(f'Транспонированная матрица с помощью атрибута "A.T"\n {A.T}')

Единичная матрица:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Транспонированная матрица с помощью функции "np.transpose"
 [[ 1  3]
 [ 0  5]
 [-1 -4]]
Транспонированная матрица с помощью метода "A.transpose"
 [[ 1  3]
 [ 0  5]
 [-1 -4]]
Транспонированная матрица с помощью атрибута "A.T"
 [[ 1  3]
 [ 0  5]
 [-1 -4]]


##### Определитель и ранг матрицы, обратная матрица

In [33]:
print(f'Определитель матрицы:\t {np.linalg.det(B)}')
print(f'Ранг матрицы:\t {np.linalg.matrix_rank(B)}')

Определитель матрицы:	 6.66133814775094e-16
Ранг матрицы:	 2


In [34]:
# Если определитель квадратной матрицы не равен  0 , то мы можем посчитать для неё обратную матрицу. 
# Это матрица, которая при умножении на исходную матрицу даёт единичную матрицу


In [35]:
print(f'Обратная матрица:\n {np.linalg.inv(B)}')

Обратная матрица:
 [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


##### Генерирование массивов с заданными свойствами

In [36]:
print(f'Массив из нулей:\n {np.zeros((3, 4))}')
print(f'Массив из едениц:\n {np.ones((3, 4))}')

Массив из нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив из едениц:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
print(f'Последовательность чисел:\t {np.arange(10)}')
print(f'Последовательность чисел от и до:\t {np.arange(2, 10)}')
print(f'Последовательность чисел с шагом:\t {np.arange(2, 10, 2)}') # шаг может быть дробным или отрицательным

Последовательность чисел:	 [0 1 2 3 4 5 6 7 8 9]
Последовательность чисел от и до:	 [2 3 4 5 6 7 8 9]
Последовательность чисел с шагом:	 [2 4 6 8]


In [40]:
# Возвращает количество значений, равномерно расставленных между заданными началом и концом отрезка включительно
np.linspace(2, 3, 10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [42]:
# Аналогична linspace, но в качестве начала и конца отрезка мы подаём не сами числа, а степени числа  10
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

##### Массивы случайных значений

In [47]:
print(f'Массив заданной формы, состоящий из чисел, взятых из равномерного распределения на отрезке [0,1):\n {np.random.sample((3, 4))}')
print(f'Аналогичный массив, взятый из нормального распределения (со средним 0 и среднеквадратическим отклонением 1):\n{np.random.randn(3, 4)}')
print(f'Массив из целых чисел в указанном диапазоне:\n {np.random.randint(0, 100, (3, 4))}')

Массив заданной формы, состоящий из чисел, взятых из равномерного распределения на отрезке [0,1):
 [[0.38593562 0.34888614 0.14618527 0.12652019]
 [0.2813262  0.13355982 0.44261879 0.14834902]
 [0.19662482 0.61272782 0.92082593 0.7432735 ]]
Аналогичный массив, взятый из нормального распределения (со средним 0 и среднеквадратическим отклонением 1):
[[ 1.60728353 -0.09455181  1.82752414  0.80815918]
 [ 0.91349842  0.98073424  0.74194895 -0.81622064]
 [-1.12958986 -0.88776898 -1.62915214 -0.46297933]]
Массив из целых чисел в указанном диапазоне:
 [[72 14 53 45]
 [31 14 44 39]
 [50 40 46 30]]


In [48]:
Ad = np.arange(-10, 0)
print(f'Случайно выбранные элементы из заранее заданного массива:\n {np.random.choice(Ad, (3, 4))}')

Случайно выбранные элементы из заранее заданного массива:
 [[ -8  -8  -7  -7]
 [-10  -3  -6  -5]
 [ -4  -5  -3  -1]]


##### Изменение размеров массива

In [53]:
ar = np.arange(12)
print(f'Создание двумерного массива:\n{ar.reshape(3, 4)}')
print(f'Создание двумерного массива если извстен 1 из параметров:\n{ar.reshape(3, -1)}')
# reshape возвращает новый массив, а resize меняет исходный
ar.resize(3, 4)
print(f'С помощью resize:\n {ar}')
print(f'Делает обратно одномерный массив:\t {ar.flatten()}')

Создание двумерного массива:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Создание двумерного массива если извстен 1 из параметров:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
С помощью resize:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Делает обратно одномерный массив:	 [ 0  1  2  3  4  5  6  7  8  9 10 11]
