In [2]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
a = np.arange(12, 24)
print('Array a:', a)

Array a: [12 13 14 15 16 17 18 19 20 21 22 23]


#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [4]:
b1 = a.reshape(3, 4)
b2 = a.reshape(6, 2)
b3 = a.reshape(4, 3)
b4 = a.reshape(2, 6)
b5 = a.reshape(12, 1)
print('Two-dimensional array 1:\n', b1)
print('Two-dimensional array 2:\n', b2)
print('Two-dimensional array 3:\n', b3)
print('Two-dimensional array 4:\n', b4)
print('Two-dimensional array 5:\n', b5)

Two-dimensional array 1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Two-dimensional array 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Two-dimensional array 3:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Two-dimensional array 4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Two-dimensional array 5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [5]:
c1 = a.reshape(3, -1)
c2 = a.reshape(-1, 2)
c3 = a.reshape(4, -1)
c4 = a.reshape(2, -1)
c5 = a.reshape(-1, 1)
print('Two-dimensional array 1:\n', c1)
print('Two-dimensional array 2:\n', c2)
print('Two-dimensional array 3:\n', c3)
print('Two-dimensional array 4:\n', c4)
print('Two-dimensional array 5:\n', c5)

Two-dimensional array 1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Two-dimensional array 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Two-dimensional array 3:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Two-dimensional array 4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Two-dimensional array 5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

`Можно`. По сути у него одна строка данных, расположенная вертикатьно - столбец.

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
ar = np.random.randn(3, 4)
print('Two-dimensial array with random values:\n', ar)

ar_flatten = ar.flatten()
print('1D array:\n', ar_flatten)

Two-dimensial array with random values:
 [[-0.52048911 -1.09787848 -2.81638829 -1.38715247]
 [ 0.92348472 -0.597933   -0.51474071  1.45220636]
 [-0.52053125  0.04573507 -0.58768217  1.19146611]]
1D array:
 [-0.52048911 -1.09787848 -2.81638829 -1.38715247  0.92348472 -0.597933
 -0.51474071  1.45220636 -0.52053125  0.04573507 -0.58768217  1.19146611]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20, 0, -2)
print('Decreasing array:', a)

Decreasing array: [20 18 16 14 12 10  8  6  4  2]


#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [8]:
b = np.arange(20, 1, -2)
print('Decreasing array:', b)

Decreasing array: [20 18 16 14 12 10  8  6  4  2]


In [9]:
print('Array "a" equals array "b":\n', a == b)

Array "a" equals array "b":
 [ True  True  True  True  True  True  True  True  True  True]


Массивы a и b ничем не отличаются. Т.к. шаг обоих массивов равен 2, не имеет значение до 0 или 1 невключительно они создаются. Количество и значения их элементов полностью совпадают.

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
a = np.zeros((2, 2))
print('Array a:\n', a)

b = np.ones((3, 2))
print('Array b:\n', b)

Array a:
 [[0. 0.]
 [0. 0.]]
Array b:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# variant 1
v = np.vstack((a, b))
print('Concatenated array:\n', v)
print("Array size:", v.size)

Concatenated array:
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array size: 10


In [12]:
# variant 2
v = np.concatenate((a, b), axis=0)
print('Concatenated array:\n', v)
print("Array size:", v.size)

Concatenated array:
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array size: 10


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [15]:
# create array a
a = np.arange(12)
print('Array a:', a)

Array a: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# reshape array a
A = a.reshape(4,3)
print('2D array A:\n', A)

2D array A:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
# transpose matrix A
At = A.transpose()
print('Transposed matrix At:\n', At)

Transposed matrix At:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [18]:
# multiply matrices A & At
B = np.dot(A, At)
print('Matrix B:\n', B)

Matrix B:
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [19]:
# show the size of matrix B
B.size

16

In [21]:
# calculate a determinant of a matrix B
print(f'The determinant of the matrix B equals {np.linalg.det(B)}')

The determinant of the matrix B equals 0.0


Вычислить обратную матрицу для матрицы B нельзя, так как ее определитель равен нулю.

#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [24]:
# initialize random function
np.random.seed(seed=42)

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [28]:
# create array c
c = np.linspace(0, 16, 16, endpoint=False)
print('Array c:', c)

Array c: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [29]:
# reshape array c
C = c.reshape(4, 4)
print('Squared matrix C:\n', C)

Squared matrix C:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [36]:
# add matrices B & C, variant 1
D = B + (C * 10)
print('Matrix D:\n', D)

Matrix D:
 [[  5.  24.  43.  62.]
 [ 54. 100. 146. 192.]
 [103. 176. 249. 322.]
 [152. 252. 352. 452.]]


In [53]:
# add matrices B & C, variant 2
D = np.add(B, np.dot(C, 10))
print('Matrix D:\n', D)

Matrix D:
 [[  5.  24.  43.  62.]
 [ 54. 100. 146. 192.]
 [103. 176. 249. 322.]
 [152. 252. 352. 452.]]


In [54]:
# calculate the determinant and rank of the matrix D
print(f'The determinant of the matrix B equals {np.linalg.det(D)}')
print(f'The rank of the matrix B equals {np.linalg.matrix_rank(D)}')

The determinant of the matrix B equals -7.685903354004529e-25
The rank of the matrix B equals 2


In [55]:
# calculate inverse matrix D_inv
D_inv = np.linalg.inv(D)
print(f'Inverse matrix:\n', D_inv)

Inverse matrix:
 [[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [56]:
# replace positive elements of the matrix D_inv with 1
i, j = np.where(D_inv > 0)
D_inv[i, j] = 1

In [57]:
# replace negative elements of the matrix D_inv with 0
i, j = np.where(D_inv < 0)
D_inv[i, j] = 0

In [58]:
print('Replaced matrix D_inv:\n', D_inv)

Replaced matrix D_inv:
 [[1. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [60]:
# create matrix E with zeros values
E = np.zeros((4, 4))
print('Matrix E:\n', E)

Matrix E:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [61]:
# fill matrix E with values from matrices B, using matrix D as mask
i, j = np.where(D_inv == 1)
E[i, j] = B[i, j]
print('Matrix E:\n', E)

Matrix E:
 [[  5.  14.   0.  32.]
 [  0.  50.  86.   0.]
 [ 23.   0.   0. 212.]
 [  0. 122.   0.   0.]]


In [62]:
# fill matrix E with values from matrices C, using matrix D as mask
i, j = np.where(D_inv == 0)
E[i, j] = C[i, j]
print('Matrix E:\n', E)

Matrix E:
 [[  5.  14.   2.  32.]
 [  4.  50.  86.   7.]
 [ 23.   9.  10. 212.]
 [ 12. 122.  14.  15.]]
