In [37]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [38]:
a = np.arange(12, 24)
print('Array a:', a)

Array a: [12 13 14 15 16 17 18 19 20 21 22 23]


#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [39]:
b1 = a.reshape(3, 4)
b2 = a.reshape(6, 2)
b3 = a.reshape(4, 3)
b4 = a.reshape(2, 6)
b5 = a.reshape(12, 1)
print('Two-dimensional array 1:\n', b1)
print('Two-dimensional array 2:\n', b2)
print('Two-dimensional array 3:\n', b3)
print('Two-dimensional array 4:\n', b4)
print('Two-dimensional array 5:\n', b5)

Two-dimensional array 1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Two-dimensional array 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Two-dimensional array 3:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Two-dimensional array 4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Two-dimensional array 5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [40]:
c1 = a.reshape(3, -1)
c2 = a.reshape(-1, 2)
c3 = a.reshape(4, -1)
c4 = a.reshape(2, -1)
c5 = a.reshape(-1, 1)
print('Two-dimensional array 1:\n', c1)
print('Two-dimensional array 2:\n', c2)
print('Two-dimensional array 3:\n', c3)
print('Two-dimensional array 4:\n', c4)
print('Two-dimensional array 5:\n', c5)

Two-dimensional array 1:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Two-dimensional array 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Two-dimensional array 3:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Two-dimensional array 4:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Two-dimensional array 5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

`Можно`. По сути у него одна строка данных, расположенная вертикатьно - столбец.

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [41]:
ar = np.random.randn(3, 4)
print('Two-dimensial array with random values:\n', ar)

ar_flatten = ar.flatten()
print('1D array:\n', ar_flatten)

Two-dimensial array with random values:
 [[ 0.29870072  0.78023217 -0.06048491  1.59465847]
 [ 0.16582609 -0.74216023  0.08261279 -0.83302656]
 [-1.57870814 -0.78347286  0.05524314  0.33046563]]
1D array:
 [ 0.29870072  0.78023217 -0.06048491  1.59465847  0.16582609 -0.74216023
  0.08261279 -0.83302656 -1.57870814 -0.78347286  0.05524314  0.33046563]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [42]:
a = np.arange(20, 0, -2)
print('Decreasing array:', a)

Decreasing array: [20 18 16 14 12 10  8  6  4  2]


#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [43]:
b = np.arange(20, 1, -2)
print('Decreasing array:', b)

Decreasing array: [20 18 16 14 12 10  8  6  4  2]


In [44]:
print('Array "a" equals array "b":\n', a == b)

Array "a" equals array "b":
 [ True  True  True  True  True  True  True  True  True  True]


Массивы a и b ничем не отличаются. Т.к. шаг обоих массивов равен 2, не имеет значение до 0 или 1 невключительно они создаются. Количество и значения их элементов полностью совпадают.

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [45]:
a = np.zeros((2, 2))
print('Array a:\n', a)

b = np.ones((3, 2))
print('Array b:\n', b)

Array a:
 [[0. 0.]
 [0. 0.]]
Array b:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [46]:
# variant 1
v = np.vstack((a, b))
print('Concatenated array"\n', v)
print("Array size:", v.size)

Concatenated array"
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array size: 10


In [47]:
# variant 2
v = np.concatenate((a, b), axis=0)
print('Concatenated array"\n', v)
print("Array size:", v.size)

Concatenated array"
 [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array size: 10
